Vagrant.configure("2") do |c|
  c.vm.box = "precis64-chef-ruby-java-mvn2"
  c.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.10_provisionerless.box"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.hostname = "default-ubuntu-1210.vagrantup.com"
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "256"]
  end
end