Vagrant.configure("2") do |c|
  c.vm.box = "precise64"
  c.vm.box_url = "http://files.vagrantup.com/precise64.box"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.hostname = "package-ubuntu-1204.vagrantup.com"
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "512"]
    p.customize ["modifyvm", :id, "--cpus", "4"]
  end
end